name: Build and Push to Docker Hub
on:
  workflow_call:
    inputs:
      docker_org:
        type: string
        default: frederickwong
      docker_image:
        type: string
        default: sandbox
      platforms:
        type: string
        default: linux/amd64
      build-date:
        type: string
        default: "1999-09-19"
#       version:
#         required: true
#         type: string
# - need major/minor/patch
# - need rc true/false
# - need tag as a string array
# - need build args
# - docker username/password should be passed as secret here
# - how to build if dockerfile is in sub-directory?
jobs:
  build_and_push:
    runs-on:  ubuntu-latest
    env:
      TARGET: ${{ inputs.docker_org }}/${{ inputs.docker_image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker Meta Data
      id:   meta
      uses: docker/metadata-action@v4
      with:
        images: |
          frederickwong/sandbox
        tags: |
          type=semver,pattern={{version}},value=1.2.3
          type=semver,pattern={{major}}.{{minor}},value=1.2.3
          type=semver,pattern={{version}}-{{ $inputs.build-date }},value=1.2.3
    - name: printenv
      run:  printenv
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
#        build-args:
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
#         tags: |
#           ${{ env.TARGET }}:${{ env.version }}
#           ${{ env.TARGET }}:latest
