name: Get Latest Tag
on:
  workflow_dispatch:
jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
      # checkout the current branch (seleted by workflow_dispatch)
      # and fetch all history from the repo, otherwise
      # it will only fetch the last commit and we will not be
      # able to find out the commit sha of the latest tag
      # if there are more than one commit after the latest tag in the
      # commit path
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      #          ref: main
      - name: Get Latest Tag
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo ${LATEST_TAG}
          LATEST_TAG_SHA=$(git rev-list -n 1 ${LATEST_TAG})
          echo ${LATEST_TAG_SHA}
