name: Save Shell Output to Env
on:
  workflow_dispatch:
jobs:
  output_job:
    runs-on: ubuntu-latest
    outputs:
#      current_date: ${{ steps.date_job.outputs.current_date }}
      output: ${{ steps.date_job.outputs.current_date }}
    steps:
      - id:   date_job
        name: Save Date to Job Output
        shell: bash
        run:  |
          echo "current_date=123456" >> "$GITHUB_OUTPUT"
#          echo "current_date=`date +'%Y-%m-%d'`" >> $GITHUB_OUTPUT
#       - name: Save Date to State
#         run:  echo "current_date=${date + '%Y-%m-%d'}" >> $GITHUB_STATE
      - name: Echo from the same job
        run: echo ${{ steps.date_job.outputs.current_date }}
  echo_date_to_console:
    runs-on: ubuntu-latest
    needs: output_job
    steps:
      - name: Echo Job Date to Console
        run:  echo "current date ${{needs.output_job.outputs.output}}"
        
