name: Save Shell Output to Env
on:
  workflow_dispatch:
jobs:
  save_date_to_job_output:
    runs-on: ubuntu-latest
    outputs:
#      current_date: ${{ steps.date_job.outputs.current_date }}
      output: "abcd"
    steps:
      - id:   date_job
        name: Save Date to Job Output
        shell: bash
        run:  |
          echo "current_date=123456" >> "$GITHUB_OUTPUT"
#          echo "current_date=`date +'%Y-%m-%d'`" >> $GITHUB_OUTPUT
#       - name: Save Date to State
#         run:  echo "current_date=${date + '%Y-%m-%d'}" >> $GITHUB_STATE
      - name: Echo from the same job
        run: echo ${{ steps.date_job.outputs.current_date }}
  echo_date_to_console:
    runs-on: ubuntu-latest
    needs: save_date_to_job_output
    steps:
      - name: Echo Job Date to Console
        env:
          current_date: ${{needs.save_date_to_job_ouput.outputs.output}}
        run:  printenv
        
