# there are 3 ways to share, via GITHUB_ENV, GITHUB_OUTPUT and GITHUB_STATE
# env is within the job, output is across the jobs, state is not discussed here.
name: Share Shell Outputs to Jobs/Steps
on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    # setup job's output variable and the values
    outputs:
      current_date: ${{ steps.get_date.outputs.result }}
      current_time: ${{ env.current_time }}
    steps:
      # step "id" for identifying where to get the output
      - id:   get_date
        name: Get Date and Save Result to Step Output
        # "shell" is optional if it is not bash dependent
        shell: bash
        # new syntax for setting step output using shell
        # pipe "|" is for use with multiple shell commands
        run:  |
          echo "result=`date +'%Y-%m-%d'`" >> "$GITHUB_OUTPUT"
      - name: Echo Result within the Same Job
        run:  echo ${{ steps.get_date.outputs.result }}
      - name: Get Time and Save Result to Env
        run:  echo "current_time=`date +'%T'`" >> "$GITHUB_ENV"
      - name: Echo Time from Env
        run:  echo "current time is $current_time"
  show_result:
    runs-on: ubuntu-latest
    # wait until "setup" is completed
    needs: setup
    steps:
      - name: Echo Outputs from Previous Job
        run:  |
          echo "current date is ${{ needs.setup.outputs.current_date }}"
          echo "current time is ${{ needs.setup.outputs.current_time }}"
