name: Tag Trigger
on:
  push:
    tags:
      - "*"

jobs:
  tag-triggerred:
    runs-on: ubuntu-latest
    steps:
      - name: print ref
        run: echo ${{ github.ref }}
      - name: print ref 2
        run: echo $GITHUB_REF
      - name: print head ref
        run: echo $GITHUB_HEAD_REF
      - name: checkout code
        uses: actions/checkout@v3
      - name: Get SHA
        run: |
          echo ${{ github.ref }}
          echo ${{ github.sha }}
          cat ./blah
