name: Test Get Latest Tag
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: "Branch/Commit ID"
        default: main
jobs:
  test-get-latest-tag:
    if: |
      inputs.ref == 'new-branch' ||
      inputs.ref == 'test'
    uses: frederickcwong/.github/.github/workflows/get-latest-tag.yml@main
    with:
      ref: ${{inputs.ref}}
  echo-result:
    runs-on: ubuntu-latest
    needs: [test-get-latest-tag]
    if: |
      inputs.ref == 'new-branch' ||
      inputs.ref == 'test'
    steps:
      - name: Echo Result
        run: |
          echo "tag: ${{needs.test-get-latest-tag.outputs.tag}}"
          echo "sha: ${{needs.test-get-latest-tag.outputs.sha}}"
