# IMPORTANT - do not use quote for tag/branch/repo names. it will break the (bash and yaml) code.
# just stick to valid docker image tag (a-z A-Z 0-9 - . _) and backslash /.
# although we can get the tag with quotes and manupilate it in shell using variables,
# it wont work across jobs because in order to reference output from another job (like from a reusable
# workflow), it must be done via "needs.<job-id>" or "needs.<step-id>". These are not variables in the
# shell. They are replaced with the actual text content before the script is executed, similar to
# typing the content on the command line which will cause a lot of issues when the script is executed.

# there are two ways to get the tag
# - get it from $github.ref_name if it is a push tag event
# - get it using the commit ID with command "git describe --tags --abbrev=0" (latest tag)
#
# both can be stored
name: Push Trigger to Build Image
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      ref:
        description: Branch name or commit hash (branch selection above is ignored)
        required: true
        type: string
        default: main
      latest:
        description: Update "latest" tag?
        required: true
        type: boolean
        default: false
  schedule:
    - cron: "0 10 * * *"

jobs:
  check-base-image:
    runs-on: ubuntu-latest
    outputs:
      need-update: ${{steps.check.outputs.needs-updating}}
    steps:
      - id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/alpine:latest
          image: frederickwong/sandbox:latest
          platforms: linux/amd64,linux/arm64

  # get the sha and tag from github context (push tag action)
  get-push-params:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{steps.get-params.outputs.sha}}
      tag: ${{steps.get-params.outputs.tag}}
    steps:
      - id: get-params
        name: Get Push Tag Params
        # see important note @ get-params job
        # no conditional handling needed because github.sha and github.ref
        # are required values in every action. I just needed to ignore them
        # if the event is not a push
        shell: bash
        run: |
          echo "sha=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
          echo "tag=${GITHUB_REF_NAME}" >> "$GITHUB_OUTPUT"

  get-dispatch-params:
    uses: frederickcwong/.github/.github/workflows/get-latest-tag.yml@main
    with:
      ref: "${{inputs.ref}}"

  get-schedule-params:
    uses: frederickcwong/.github/.github/workflows/get-latest-tag.yml@main
    with:
      ref: "main"

  # IMPORTANT NOTE
  #
  # there is an issue with the "needs" logic
  # "needs" is a logical AND operation, meaning it needs all jobs listed
  # if any of them failed or skipped, this job will not run.
  # ideally, we want "get-dispatch-params" runs only when it is a dispatch
  # event, etc. (this can be done by adding "if" condition in their jobs above)
  # however, adding "if" condition to the jobs will "skip" the jobs causing this
  # "get-params" job skipped.
  # There is another solution to this limitation as described in the link below
  # but it sounds like more tests/work/complications.
  # https://stackoverflow.com/questions/66343052/github-actions-or-operator-for-needs-clause
  # Hence my short-term solution is to let all of them runs, and use conditional statements
  # inside each job to determine the job's outputs (default random values vs
  # actual values).
  get-params:
    runs-on: ubuntu-latest
    needs:
      [
        get-push-params,
        get-dispatch-params,
        get-schedule-params,
        check-base-image,
      ]
    outputs:
      sha: ${{steps.get-params.outputs.sha}}
      tag: ${{steps.get-params.outputs.tag}}
      is-release: ${{steps.get-params.outputs.is-release}}
      latest: ${{steps.get-params.outputs.latest}}
      build-image: ${{steps.get-params.outputs.build-image}}
    steps:
      - id: get-params
        shell: bash
        run: |
          function isRelease() {
            [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo 'true' || echo 'false'
          }

          # sanitize git tag to satisfy docker requirements
          function sanitizeTag() {
            # replace empty tag with 'no-tag'
            # insert '_' to tag that starts with '-'
            # insert '_' to tag that starts with '.'
            # replace all non-valid characters with '-'
            # and limit number of characters to 128
            result=$(echo $1 | sed         \
              -e 's/^$/no-tag/'            \
              -e 's/^\(\-\)/_\1/'          \
              -e 's/^\(\.\)/_\1/'          \
              -e 's/[^a-zA-Z0-9\-_\.]/-/g' \
            | cut -c 1-128)
            echo $result
          }

          # push tag
          #
          # assume tag push event is always a release event if the tag is in
          # semver format, which will also tag the image with latest tag
          #
          # docker image tags:
          #   - "<tag>-YYYY-MM-DD" (semver format)
          #   - "latest" (semver format)
          #   - "<tag>" (not semver format)
          if [[ ${GITHUB_EVENT_NAME}  == 'push' ]]; then

            sha='${{needs.get-push-params.outputs.sha}}'
            tag='${{needs.get-push-params.outputs.tag}}'
            tag=${sanitizeTag $tag}
            is_release=${isRelease $tag}
            latest=${is_release}
            build_image='true'

          # workflow dispatch
          #
          # if user did not request "latest", the image will not be tagged with "latest" tag
          # if user requested "latest", the image will be tagged only if the tag is in semver format
          #
          # docker image tags:
          #   - "major.minor.patch-YYYY-MM-DD" (semver)
          #   - "latest" (semver && latest requested)
          #   - "tag" (not semver)
          elif [[ ${GITHUB_EVENT_NAME} == 'workflow_dispatch' ]]; then

            sha='${{needs.get-dispatch-params.outputs.sha}}'
            tag='${{needs.get-dispatch-params.outputs.tag}}'
            tag=${sanitizeTag $tag}
            is_release=$(isRelease $tag)
            latest=$([[ '${{inputs.latest}}' == 'true' && ($is_release == 'true') ]] && echo 'true' || echo 'false')
            build_image="true"

          # schedule
          #
          # its purpose is to update the base image periodically and it is intended for the "latest" release
          # therefore, if the latest tag in the mainline is a semver, build and update the latest tag
          # otherwise, it should skip the latest tag
          #
          # docker image tags:
          #   - "major.minor.patch-YYYY-MM-DD" (semver)
          #   - "latest" (semver)
          else

            sha='${{needs.get-schedule-params.outputs.sha}}'
            tag='${{needs.get-schedule-params.outputs.tag}}'
            tag=${sanitizeTag $tag}
            is_release=$(isRelease $tag)
            latest=$([[ $is_release == 'true' ]] && echo 'true' || echo 'false')
            build_image=$([[ '${{needs.check-base-image.outputs.need-update}}' == 'true' \
              && $is_release == 'true' ]] && echo 'true' || echo 'false')
          fi

          m_title="Build: ${GITHUB_REPOSITORY}@${tag}"

          m_body=$(cat <<EOF
          event-type:    ${GITHUB_EVENT_NAME}
          build-image:   ${build_image}
          tag:           ${tag}
          sha:           ${sha}
          is-release:    ${is_release}
          need-latest:   ${latest}
          EOF
          )
          if [[ ${GITHUB_EVENT_NAME} == 'schedule' && ${is_release} == 'false']]; then
            m_body="${m_body}\n - WARNING: Schedule event encountered a non-semver tag!"
          fi

          echo "sha=${sha}" >> "$GITHUB_OUTPUT"
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          echo "is-release=${is_release}" >> "$GITHUB_OUTPUT"
          echo "latest=${latest}" >> "$GITHUB_OUTPUT"
          echo "need-building=${need_building}" >> "$GITHUB_OUTPUT"
          echo "shoutrrr-title=$m_title" >> "$GITHUB_OUTPUT"

          # output does not accept multi-line string, use env instead
          echo "shoutrrr_body<<EOF" >> "$GITHUB_ENV"
          echo "$m_body" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      # xxx - need to test if shoutrrr url is available, otherwise skip the step
      - uses: containrrr/shoutrrr-action@v1
        with:
          url: ${{ secrets.SHOUTRRR_URL }}
          title: ${{steps.get-params.outputs.shoutrrr-title}}
          message: ${{env.shoutrrr_body}}

  # build the image with tags based on tag is in semver format or not
  build:
    needs: [get-params]
    if: ${{needs.get-params.outputs.build-image == 'true'}}
    uses: ./.github/workflows/build-push-image.yml
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      ref: ${{needs.get-params.outputs.sha}}
      org: frederickwong
      image: sandbox
      platforms: linux/amd64,linux/arm64
      base-tag: ${{needs.get-params.outputs.tag}}
      need-latest: ${{needs.get-params.outputs.latest == 'true'}}
      need-build-date: ${{needs.get-params.outputs.is-release == 'true'}}
      build-date-tz: America/Los_Angeles
