# "schedule" always build the image from the "main" using the latest tag

# xxx: what happen if there is no tag in the "main" branch?
name: Test Regex
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true
      no-tag:
        type: string
        required: true
        default: "no-tag"
      start-hyphen:
        type: string
        required: true
        default: "_"
      start-dot:
        type: string
        required: true
        default: "_"
      bad-char:
        type: string
        required: true
        default: "-"
jobs:
  check-image:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          # replace empty tag with 'no-tag'
          # insert '_' to tag starts with '-'
          # insert '_' to tag starts with '.'
          # replace all non-valid characters with '-'
          # and limit number of characters to 128
          result=$(echo '${{inputs.tag}}' | sed               \
            -e 's/^$/${{inputs.no-tag}}/'                   \
            -e 's/^\(\-\)/${{inputs.start-dot}}\1/'         \
            -e 's/^\(\.\)/${{inputs.start-hyphen}}\1/'      \
            -e 's/[^a-zA-Z0-9\-_\.]/${{inputs.bad-char}}/g' \
            | cut -c 1-128)
          echo $result
