#

# if d.d.d, build full semver (multi-tag image)
# otherwise, build special name (single tag image)

name: Push Trigger to Build Image
on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      ref:
        description: Branch name or commit hash (branch selection above is ignored)
        required: true
        type: string
        default: main

jobs:
  # get the sha and tag from github context (push tag action)
  get-push-params:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{steps.get-params.outputs.sha}}
      tag: ${{steps.get-params.outputs.tag}}
      is-semver: ${{steps.get-params.outputs.is-semver}}
    steps:
      - id: get-params
        name: Get Push Tag Params
        # see important note @ get-params job
        # no conditional handling needed because github.sha and github.ref
        # are required values in every action. I just needed to ignore them
        # if the event is not a push
        run: |
          echo "sha=${{github.sha}}" >> "$GITHUB_OUTPUT"
          tag=$(echo "${{github.ref}}" | awk -F/ '{print $3}')
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          is_semver=$([[ $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo 'true' || echo 'false')
          echo "is-semver=${is_semver}" >> "$GITHUB_OUTPUT"

  get-dispatch-params:
    if: ${{github.event_name == 'workflow_dispatch'}}
    uses: frederickcwong/.github/.github/workflows/get-latest-tag.yml@main
    with:
      ref: ${{inputs.ref}}

  # IMPORTANT NOTE
  #
  # there is an issue with the "needs" logic
  # "needs" is a logical AND operation, meaning it needs all jobs listed
  # if any of them failed or skipped, this job will not run.
  # ideally, we want "get-dispatch-params" runs only when it is a dispatch
  # event, etc. (this can be done by adding "if" condition in their jobs above)
  # however, adding "if" condition to the jobs will "skip" the jobs causing this
  # "get-params" job skipped.
  # There is another solution to this limitation as described in the link below
  # but it sounds like more tests/work/complications.
  # https://stackoverflow.com/questions/66343052/github-actions-or-operator-for-needs-clause
  # Hence my short-term solution is to let all of them runs, and use conditional statements
  # inside each job to determine the job's outputs (default random values vs
  # actual values).
  get-params:
    runs-on: ubuntu-latest
    needs: [get-push-params, get-dispatch-params]
    outputs:
      sha: ${{steps.get-params.outputs.sha}}
      tag: ${{steps.get-params.outputs.tag}}
      is-semver: ${{steps.get-params.outputs.is-semver}}
    steps:
      - id: get-params
        run: |
          if [[ ${{github.event_name == 'push'}} ]]
          then
            echo "sha=${{needs.get-push-params.outputs.sha}}" >> "$GITHUB_OUTPUT"
            echo "tag=${{needs.get-push-params.outputs.tag}}" >> "$GITHUB_OUTPUT"
            echo "is-semver=${{needs.get-push-params.outputs.is-semver}}" >> "$GITHUB_OUTPUT"
          else
            echo "sha=${{needs.get-dispatch-params.outputs.sha}}" >> "$GITHUB_OUTPUT"
            echo "tag=${{needs.get-dispatch-params.outputs.tag}}" >> "$GITHUB_OUTPUT"
            echo "is-semver=false" >> "$GITHUB_OUTPUT"
          fi

  # build the image with tags based on tag is in semver format or not
  build:
    needs: [get-params]
    uses: frederickcwong/.github/.github/workflows/docker-build-push.yml@main
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      repo-sha: ${{needs.get-params.outputs.sha}}
      org: frederickwong
      image: sandbox
      platforms: linux/amd64,linux/arm64
      semver: ${{needs.get-params.outputs.tag}}
      tag-full-semver: ${{needs.get-params.outputs.is-semver == 'true'}}
      tag-major-minor: ${{needs.get-params.outputs.is-semver == 'true'}}
      tag-major: false
      tag-latest: ${{needs.get-params.outputs.is-semver == 'true'}}
      tag-build-date: ${{needs.get-params.outputs.is-semver == 'true'}}
      build-date-tz: America/Los_Angeles
      tag-special-name: ${{needs.get-params.outputs.is-semver == 'false'}}
      special-name: ${{needs.get-params.outputs.tag}}
