# "schedule" always build the image from the "main" using the latest tag

# xxx: what happen if there is no tag in the "main" branch?
name: Rebuild Image if Base Image Updated
on:
  workflow_dispatch:

jobs:
  check-image:
    runs-on: ubuntu-latest
    outputs:
      need-update: ${{steps.check.outputs.needs-updating}}
    steps:
      - name: check if base image has changed
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/alpine:3.18.2
          image: frederickwong/sandbox:latest
      - run: |
          echo "need-updating: ${{steps.check.outputs.needs-updating}}"
