#

# need to check the tag and see if it is d.d.d
# if d.d.d, build full semver (multi-tag image)
# otherwise, build special name (single tag image)
name: Push Trigger to Build Image
on:
  push:
    tags:
      - "*"
jobs:
  # get the sha and tag from github context
  get-params:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{steps.get-params.outputs.sha}}
      tag: ${{steps.get-params.outputs.tag}}
      is-semver: ${{steps.get-params.outputs.is-semver}}
    steps:
      - id: get-params
        name: Get Push Tag Params
        run: |
          echo "sha=${{github.sha}}" >> "$GITHUB_OUTPUT"
          tag=$(echo "${{github.ref}}" | awk -F/ '{print $3}')
          echo "tag=${tag}" >> "$GITHUB_OUTPUT"
          is_semver=$([[ $tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo 'true' || echo 'false')
          echo "is-semver=${is_semver}" >> "$GITHUB_OUTPUT"

  # build the image with tags based on tag is in semver format or not
  build:
    needs: [get-params]
    uses: frederickcwong/.github/.github/workflows/docker-build-push.yml@main
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      repo-sha: ${{needs.get-params.outputs.sha}}
      org: frederickwong
      image: sandbox
      platforms: linux/amd64,linux/arm64
      semver: ${{needs.get-params.outputs.tag}}
      tag-full-semver: ${{needs.get-params.outputs.is-semver == 'true'}}
      tag-major-minor: ${{needs.get-params.outputs.is-semver == 'true'}}
      tag-major: false
      tag-latest: ${{needs.get-params.outputs.is-semver == 'true'}}
      tag-build-date: ${{needs.get-params.outputs.is-semver == 'true'}}
      build-date-tz: America/Los_Angeles
      tag-special-name: ${{needs.get-params.outputs.is-semver == 'false'}}
      special-name: ${{needs.get-params.outputs.tag}}
