name: Tag Name
on:
  push:
    tags:
      - "**"
jobs:
  tag-name:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{steps.blah.outputs.tag}}
    steps:
      - id: blah
        run: |
          echo 'sha=${{github.sha}}' >> "$GITHUB_OUTPUT"
          tag=${GITHUB_REF_NAME//\'/\\\'}
          echo $'tag=${tag}' >> "$GITHUB_OUTPUT"
          is_semver=$([[ $'${tag}' =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] && echo 'true' || echo 'false')
          echo "is-semver=${is_semver}" >> "$GITHUB_OUTPUT"
          printenv
          echo $github
