# xxx: need to update the build script and change special name usage

# "dispatch" will use whatever tag to do the build, and attach the tag directly to the image

name: Test Dispatch Trigger
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        default: main
jobs:
  build:
    uses: frederickcwong/.github/.github/workflows/docker-build-and-push.yml@main
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
    with:
      ref: "main"
      org: frederickwong
      image: sandbox
      platforms: linux/amd64,linux/arm64
      build-args: |
        VERSION=1.2.3
        STUFF=abc
      base-tag: 4.0.0
