# "schedule" always build the image from the "main" using the latest tag

# xxx: what happen if there is no tag in the "main" branch?
name: Test Regex
on:
  workflow_dispatch:

jobs:
  check-image:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          tag='-abc-def'
          tag=$(echo $tag | sed \
            -e 's/^$/no-tag/' \
            -e 's/^\(\-\)/_\1/' \
            -e 's/^\(\.\)/_\1/' \
            -e 's/[^a-zA-Z0-9\-_\.]/-/g' \
          )
          echo $tag
